### ISSUE TITLE
Possible to add new sources?

### ISSUE THREAD

**Issue by beepFTW** [cuongpnh/mangayou#1]
Or is all information pulled from mangayou.com?

**Comment by cuongpnh** [comment]
Yah, all information pulled from mangayou.com

**Comment by beepFTW** [comment]
Oh alright, and can you release the apk? I cannot build it on my end. I want to try this out!

**Comment by cuongpnh** [comment]
Download link for apk here
http://www.mediafire.com/download/yai6dalpm6cgid3/us.cuongpnh.mobile.mangayou-1.apk
Currently,  mangayou has some issues about API, such as pagination and order, hope they will fix those soon.
